### ISSUE TITLE
Enable dark mode

### ISSUE THREAD

**Issue by notpushkin** [OpenIndiana/oi-docs#269]
The website is currently fixed in a light mode. Adding a dark mode would make it easier on the eyes of users working in the dark and more accessible in general (e.g. for people with light sensitivity). To do that in Material for MkDocs, you can change `theme.palette` to look like this:

```yml
- media: "(prefers-color-scheme)"
  toggle:
    icon: material/brightness-auto
    name: Switch to light mode

- media: "(prefers-color-scheme: light)"
  scheme: default
  primary: white
  toggle:
    icon: material/brightness-7
    name: Switch to dark mode

- media: "(prefers-color-scheme: dark)"
  scheme: slate
  primary: black
  toggle:
    icon: material/brightness-4
    name: Switch to system preference
```

There’s a bunch of tweaks you can make: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle

Let me know if you need any help!
